// AUTO-GENERATED — ne pas éditer manuellement
// Source: scripts/scan-ecosystem.cjs
// Run: node scripts/scan-ecosystem.cjs
// Generated: 2026-02-17T14:02:11.100Z
/* eslint-disable */
window.ECOSYSTEM_DATA = [
  {
    name: 'achievements-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 234,
    description: 'Page Achievements Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'achievements-demo.html',
  },
  {
    name: 'analytics.html',
    category: 'pages',
    status: 'prod',
    loc: 173,
    description: 'Dashboard analytique',
    dependencies: [],
    path: 'analytics.html',
  },
  {
    name: 'audio-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 337,
    description: 'Page Audio Demo',
    dependencies: [],
    path: 'audio-demo.html',
  },
  {
    name: 'build.html',
    category: 'pages',
    status: 'prod',
    loc: 787,
    description: 'Builder Hub — Yggdrasil paths, formations, ecosystem',
    dependencies: [
      'security.js',
      'journey-data.js',
      'journey-progress.js',
      'journey.js',
      'index.js',
      'build.css',
      'journey.css',
      'viking-bg.css',
      'formation-panel.css',
      'skill-tree.css',
      'builder-profile.css',
      'github-timeline.css',
      'learn-build.css',
      'yggdrasil-unified.css',
      'dashboard-components.css',
    ],
    path: 'build.html',
  },
  {
    name: 'burns.html',
    category: 'pages',
    status: 'prod',
    loc: 310,
    description: 'Hall of Flames — tracker de burns $asdfasdfa',
    dependencies: [
      'security.js',
      'burns.js',
      'ecosystem.js',
      'index.js',
      'ecosystem.css',
      'burns.css',
    ],
    path: 'burns.html',
  },
  {
    name: 'contextual-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 226,
    description: 'Page Contextual Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'contextual-demo.html',
  },
  {
    name: 'deep-learn.html',
    category: 'pages',
    status: 'prod',
    loc: 1178,
    description: 'Complete Guide — K-Score, philosophie, mécanique',
    dependencies: ['deep-learn.js', 'index.js', 'system.css'],
    path: 'deep-learn.html',
  },
  {
    name: 'discovery-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 280,
    description: 'Page Discovery Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'discovery-demo.html',
  },
  {
    name: 'easter-eggs-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 318,
    description: 'Page Easter Eggs Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'easter-eggs-demo.html',
  },
  {
    name: 'ecosystem-map.html',
    category: 'pages',
    status: 'prod',
    loc: 1443,
    description: "Command Center — carte interactive de l'écosystème",
    dependencies: ['ecosystem-data.js'],
    path: 'ecosystem-map.html',
  },
  {
    name: 'forecast.html',
    category: 'pages',
    status: 'prod',
    loc: 251,
    description: 'Predictions — interface de paris',
    dependencies: ['forecast.js', 'ecosystem.js', 'index.js', 'ecosystem.css', 'forecast.css'],
    path: 'forecast.html',
  },
  {
    name: 'games.html',
    category: 'pages',
    status: 'prod',
    loc: 735,
    description: 'Arcade Hub — collection de 9 mini-jeux',
    dependencies: [
      'index.js',
      'security.js',
      'utils.js',
      'config.js',
      'asdf.js',
      'engage.js',
      'shop.js',
      'avatar.js',
      'solana.js',
      'api.js',
      'state.js',
      'rotation.js',
      'leaderboard.js',
      'competitive.js',
      'grid.js',
      'modal.js',
      'rpgstate.js',
      'character.js',
      'daily.js',
      'npcs.js',
      'quests.js',
      'events.js',
      'minigames.js',
      'skilltrees.js',
      'inventory.js',
      'achievements.js',
      'battle.js',
      'equipment.js',
      'trading.js',
      'cosmetics.js',
      'premium-effects.js',
      'combat-animations.js',
      'reward-feedback.js',
      'factions.js',
      'battle-grid.js',
      'summons.js',
      'deck-builder.js',
      'story-gates.js',
      'quest-items.js',
      'faction-skills.js',
      'quests-expanded.js',
      'events-expanded.js',
      'tutorial-combat.js',
      'effects-integration.js',
      'placeholders.js',
      'particles.js',
      'canvas.js',
      'catalog.js',
      'collections.js',
      'toast.js',
      'filters.js',
      'itemCard.js',
      'preview.js',
      'sync.js',
      'favorites.js',
      'purchase.js',
      'currency.js',
      'ui.js',
      'audio.js',
      'profile.js',
      'settings.js',
      'timing-config.js',
      'validation.js',
      'scoring.js',
      'lifecycle.js',
      'input.js',
      'intervals.js',
      'timing.js',
      'juice.js',
      'tokencatcher.js',
      'burnrunner.js',
      'scamblaster.js',
      'cryptoheist.js',
      'whalewatch.js',
      'stakestacker.js',
      'dexdash.js',
      'burnorhold.js',
      'liquiditymaze.js',
      'pumparena.js',
      'engine.js',
      'main.js',
      'arcade-hub.js',
      'cosmetics-btn.js',
      'ecosystem.js',
      'ecosystem.css',
      'games.css',
      'games-arcade.css',
      'viking-bg.css',
      'shop.css',
      'shop-animations.css',
      'valhalla.css',
    ],
    path: 'games.html',
  },
  {
    name: 'holdex.html',
    category: 'pages',
    status: 'prod',
    loc: 283,
    description: 'Token Tracker — intégration HolDex',
    dependencies: [
      'security.js',
      'holdex.js',
      'ecosystem.js',
      'index.js',
      'ecosystem.css',
      'holdex.css',
    ],
    path: 'holdex.html',
  },
  {
    name: 'ignition.html',
    category: 'pages',
    status: 'dev',
    loc: 583,
    description: 'Page Ignition',
    dependencies: [
      'security.js',
      'ignition.js',
      'ecosystem.js',
      'index.js',
      'ecosystem.css',
      'ignition.css',
    ],
    path: 'ignition.html',
  },
  {
    name: 'index.html',
    category: 'pages',
    status: 'prod',
    loc: 190,
    description: 'Hub Majestic — landing page avec fire particles',
    dependencies: [
      'hub-majestic.js',
      'index.js',
      'design-tokens.css',
      'interactions.css',
      'hub-majestic.css',
      'orbital-system.css',
      'orbital-patch.css',
    ],
    path: 'index.html',
  },
  {
    name: 'interactions-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 238,
    description: 'Page Interactions Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'interactions-demo.html',
  },
  {
    name: 'learn.html',
    category: 'pages',
    status: 'prod',
    loc: 195,
    description: 'Quick Start — intro interactive en 5 étapes',
    dependencies: ['learn.js', 'index.js', 'learn.css'],
    path: 'learn.html',
  },
  {
    name: 'me.html',
    category: 'pages',
    status: 'prod',
    loc: 426,
    description: 'Profil utilisateur',
    dependencies: ['me.js', 'design-tokens.css', 'interactions.css', 'ecosystem.css'],
    path: 'me.html',
  },
  {
    name: 'privacy.html',
    category: 'pages',
    status: 'prod',
    loc: 179,
    description: 'Page Privacy',
    dependencies: [],
    path: 'privacy.html',
  },
  {
    name: 'sound-demo.html',
    category: 'pages',
    status: 'demo',
    loc: 249,
    description: 'Page Sound Demo',
    dependencies: ['design-tokens.css', 'interactions.css'],
    path: 'sound-demo.html',
  },
  {
    name: 'squarespace-embed.html',
    category: 'pages',
    status: 'dev',
    loc: 29,
    description: 'Page Squarespace Embed',
    dependencies: [],
    path: 'squarespace-embed.html',
  },
  {
    name: 'staking.html',
    category: 'pages',
    status: 'prod',
    loc: 153,
    description: 'Interface de staking $asdfasdfa',
    dependencies: ['staking.js', 'ecosystem.js', 'ecosystem.css', 'staking.css'],
    path: 'staking.html',
  },
  {
    name: 'terrier.html',
    category: 'pages',
    status: 'prod',
    loc: 94,
    description: 'Page Terrier',
    dependencies: ['terrier.js', 'design-tokens.css', 'terrier.css'],
    path: 'terrier.html',
  },
  {
    name: 'tools.html',
    category: 'pages',
    status: 'prod',
    loc: 468,
    description: 'Page Tools',
    dependencies: ['orbital-system.css'],
    path: 'tools.html',
  },
  {
    name: 'css/build.css',
    category: 'css',
    status: 'god',
    loc: 6360,
    description: 'Styles Build',
    dependencies: [],
    path: 'css/build.css',
  },
  {
    name: 'css/builder-profile.css',
    category: 'css',
    status: 'prod',
    loc: 279,
    description: 'Styles Builder Profile',
    dependencies: [],
    path: 'css/builder-profile.css',
  },
  {
    name: 'css/burns.css',
    category: 'css',
    status: 'prod',
    loc: 1397,
    description: 'Styles Burns',
    dependencies: [],
    path: 'css/burns.css',
  },
  {
    name: 'css/dashboard-components.css',
    category: 'css',
    status: 'prod',
    loc: 394,
    description: 'Styles Dashboard Components',
    dependencies: [],
    path: 'css/dashboard-components.css',
  },
  {
    name: 'css/design-tokens.css',
    category: 'css',
    status: 'prod',
    loc: 232,
    description: 'Styles Design Tokens',
    dependencies: [],
    path: 'css/design-tokens.css',
  },
  {
    name: 'css/ecosystem.css',
    category: 'css',
    status: 'prod',
    loc: 1018,
    description: 'Styles Ecosystem',
    dependencies: [],
    path: 'css/ecosystem.css',
  },
  {
    name: 'css/forecast.css',
    category: 'css',
    status: 'prod',
    loc: 1051,
    description: 'Styles Forecast',
    dependencies: [],
    path: 'css/forecast.css',
  },
  {
    name: 'css/formation-panel.css',
    category: 'css',
    status: 'prod',
    loc: 396,
    description: 'Styles Formation Panel',
    dependencies: [],
    path: 'css/formation-panel.css',
  },
  {
    name: 'css/games-arcade.css',
    category: 'css',
    status: 'prod',
    loc: 789,
    description: 'Styles Games Arcade',
    dependencies: [],
    path: 'css/games-arcade.css',
  },
  {
    name: 'css/games.css',
    category: 'css',
    status: 'prod',
    loc: 2722,
    description: 'Styles Games',
    dependencies: [],
    path: 'css/games.css',
  },
  {
    name: 'css/github-timeline.css',
    category: 'css',
    status: 'prod',
    loc: 660,
    description: 'Styles Github Timeline',
    dependencies: [],
    path: 'css/github-timeline.css',
  },
  {
    name: 'css/holdex.css',
    category: 'css',
    status: 'prod',
    loc: 972,
    description: 'Styles Holdex',
    dependencies: [],
    path: 'css/holdex.css',
  },
  {
    name: 'css/hub-majestic.css',
    category: 'css',
    status: 'prod',
    loc: 1295,
    description: 'Styles Hub Majestic',
    dependencies: [],
    path: 'css/hub-majestic.css',
  },
  {
    name: 'css/ignition.css',
    category: 'css',
    status: 'dev',
    loc: 1456,
    description: 'Styles Ignition',
    dependencies: [],
    path: 'css/ignition.css',
  },
  {
    name: 'css/interactions.css',
    category: 'css',
    status: 'prod',
    loc: 321,
    description: 'Styles Interactions',
    dependencies: [],
    path: 'css/interactions.css',
  },
  {
    name: 'css/journey.css',
    category: 'css',
    status: 'prod',
    loc: 430,
    description: 'Styles Journey',
    dependencies: [],
    path: 'css/journey.css',
  },
  {
    name: 'css/learn-build.css',
    category: 'css',
    status: 'prod',
    loc: 983,
    description: 'Styles Learn Build',
    dependencies: [],
    path: 'css/learn-build.css',
  },
  {
    name: 'css/learn.css',
    category: 'css',
    status: 'prod',
    loc: 596,
    description: 'Styles Learn',
    dependencies: [],
    path: 'css/learn.css',
  },
  {
    name: 'css/orbital-patch.css',
    category: 'css',
    status: 'prod',
    loc: 49,
    description: 'Styles Orbital Patch',
    dependencies: [],
    path: 'css/orbital-patch.css',
  },
  {
    name: 'css/orbital-system.css',
    category: 'css',
    status: 'prod',
    loc: 394,
    description: 'Styles Orbital System',
    dependencies: [],
    path: 'css/orbital-system.css',
  },
  {
    name: 'css/shop-animations.css',
    category: 'css',
    status: 'prod',
    loc: 494,
    description: 'Styles Shop Animations',
    dependencies: [],
    path: 'css/shop-animations.css',
  },
  {
    name: 'css/shop.css',
    category: 'css',
    status: 'prod',
    loc: 1919,
    description: 'Styles Shop',
    dependencies: [],
    path: 'css/shop.css',
  },
  {
    name: 'css/skill-tree.css',
    category: 'css',
    status: 'prod',
    loc: 269,
    description: 'Styles Skill Tree',
    dependencies: [],
    path: 'css/skill-tree.css',
  },
  {
    name: 'css/staking.css',
    category: 'css',
    status: 'prod',
    loc: 632,
    description: 'Styles Staking',
    dependencies: [],
    path: 'css/staking.css',
  },
  {
    name: 'css/system.css',
    category: 'css',
    status: 'prod',
    loc: 1710,
    description: 'Styles System',
    dependencies: [],
    path: 'css/system.css',
  },
  {
    name: 'css/terrier.css',
    category: 'css',
    status: 'prod',
    loc: 321,
    description: 'Styles Terrier',
    dependencies: [],
    path: 'css/terrier.css',
  },
  {
    name: 'css/valhalla.css',
    category: 'css',
    status: 'prod',
    loc: 1198,
    description: 'Styles Valhalla',
    dependencies: [],
    path: 'css/valhalla.css',
  },
  {
    name: 'css/viking-bg.css',
    category: 'css',
    status: 'prod',
    loc: 447,
    description: 'Styles Viking Bg',
    dependencies: [],
    path: 'css/viking-bg.css',
  },
  {
    name: 'css/yggdrasil-unified.css',
    category: 'css',
    status: 'prod',
    loc: 3798,
    description: 'Styles Yggdrasil Unified',
    dependencies: [],
    path: 'css/yggdrasil-unified.css',
  },
  {
    name: 'js/audio/engine.js',
    category: 'js',
    status: 'prod',
    loc: 252,
    description: 'Module Engine',
    dependencies: ['engine.js', 'profiles.js'],
    path: 'js/audio/engine.js',
  },
  {
    name: 'js/audio/index.js',
    category: 'js',
    status: 'prod',
    loc: 61,
    description: 'Module Index',
    dependencies: ['index.js', 'engine.js', 'profiles.js'],
    path: 'js/audio/index.js',
  },
  {
    name: 'js/audio/profiles.js',
    category: 'js',
    status: 'prod',
    loc: 407,
    description: 'Module Profiles',
    dependencies: [],
    path: 'js/audio/profiles.js',
  },
  {
    name: 'js/badge/definitions.js',
    category: 'js',
    status: 'prod',
    loc: 482,
    description: 'Module Definitions',
    dependencies: ['manager.js'],
    path: 'js/badge/definitions.js',
  },
  {
    name: 'js/badge/index.js',
    category: 'js',
    status: 'prod',
    loc: 37,
    description: 'Module Index',
    dependencies: ['index.js', 'manager.js', 'definitions.js'],
    path: 'js/badge/index.js',
  },
  {
    name: 'js/badge/manager.js',
    category: 'js',
    status: 'prod',
    loc: 461,
    description: 'Module Manager',
    dependencies: ['manager.js', 'index.js', 'event-bus.js', 'debug.js'],
    path: 'js/badge/manager.js',
  },
  {
    name: 'js/build/components/builder-profile.js',
    category: 'js',
    status: 'prod',
    loc: 408,
    description: 'Module Builder Profile',
    dependencies: ['state.js', 'github-api.js', 'dom.js', 'security.js'],
    path: 'js/build/components/builder-profile.js',
  },
  {
    name: 'js/build/components/factory-panel.js',
    category: 'js',
    status: 'prod',
    loc: 520,
    description: 'Module Factory Panel',
    dependencies: ['config.js', 'state.js', 'adapter.js', 'security.js', 'dom.js'],
    path: 'js/build/components/factory-panel.js',
  },
  {
    name: 'js/build/components/feature-tooltip.js',
    category: 'js',
    status: 'prod',
    loc: 258,
    description: 'Module Feature Tooltip',
    dependencies: ['state.js', 'dom.js', 'security.js', 'timing.js'],
    path: 'js/build/components/feature-tooltip.js',
  },
  {
    name: 'js/build/components/formation-panel.js',
    category: 'js',
    status: 'prod',
    loc: 436,
    description: 'Module Formation Panel',
    dependencies: ['state.js', 'formations-data.js', 'dom.js', 'security.js', 'phi.js'],
    path: 'js/build/components/formation-panel.js',
  },
  {
    name: 'js/build/components/github-timeline.js',
    category: 'js',
    status: 'prod',
    loc: 372,
    description: 'Module Github Timeline',
    dependencies: ['state.js', 'github-api.js', 'dom.js', 'security.js'],
    path: 'js/build/components/github-timeline.js',
  },
  {
    name: 'js/build/components/intro.js',
    category: 'js',
    status: 'prod',
    loc: 454,
    description: 'Module Intro',
    dependencies: ['config.js', 'state.js', 'security.js', 'dom.js'],
    path: 'js/build/components/intro.js',
  },
  {
    name: 'js/build/components/modal.js',
    category: 'js',
    status: 'prod',
    loc: 800,
    description: 'Module Modal',
    dependencies: ['config.js', 'state.js', 'adapter.js', 'github-api.js', 'security.js', 'dom.js'],
    path: 'js/build/components/modal.js',
  },
  {
    name: 'js/build/components/onboarding-progress.js',
    category: 'js',
    status: 'prod',
    loc: 125,
    description: 'Module Onboarding Progress',
    dependencies: ['state.js', 'dom.js', 'timing.js'],
    path: 'js/build/components/onboarding-progress.js',
  },
  {
    name: 'js/build/components/project-panel.js',
    category: 'js',
    status: 'prod',
    loc: 424,
    description: 'Module Project Panel',
    dependencies: ['config.js', 'state.js', 'adapter.js', 'github-api.js', 'security.js', 'dom.js'],
    path: 'js/build/components/project-panel.js',
  },
  {
    name: 'js/build/components/quiz.js',
    category: 'js',
    status: 'prod',
    loc: 352,
    description: 'Module Quiz',
    dependencies: ['config.js', 'state.js', 'security.js', 'dom.js'],
    path: 'js/build/components/quiz.js',
  },
  {
    name: 'js/build/components/share-button.js',
    category: 'js',
    status: 'prod',
    loc: 287,
    description: 'Module Share Button',
    dependencies: ['state.js', 'dom.js', 'security.js', 'timing.js'],
    path: 'js/build/components/share-button.js',
  },
  {
    name: 'js/build/components/skill-tree-view.js',
    category: 'js',
    status: 'prod',
    loc: 401,
    description: 'Module Skill Tree View',
    dependencies: ['state.js', 'skills-data.js', 'phi.js', 'dom.js'],
    path: 'js/build/components/skill-tree-view.js',
  },
  {
    name: 'js/build/components/streak-counter.js',
    category: 'js',
    status: 'prod',
    loc: 336,
    description: 'Module Streak Counter',
    dependencies: ['state.js', 'dom.js', 'timing.js'],
    path: 'js/build/components/streak-counter.js',
  },
  {
    name: 'js/build/components/tracks.js',
    category: 'js',
    status: 'prod',
    loc: 383,
    description: 'Module Tracks',
    dependencies: ['config.js', 'state.js', 'security.js', 'dom.js'],
    path: 'js/build/components/tracks.js',
  },
  {
    name: 'js/build/components/tree.js',
    category: 'js',
    status: 'prod',
    loc: 553,
    description: 'Module Tree',
    dependencies: [
      'config.js',
      'state.js',
      'adapter.js',
      'modal.js',
      'burn-api.js',
      'phi.js',
      'security.js',
      'index.js',
      'dom.js',
    ],
    path: 'js/build/components/tree.js',
  },
  {
    name: 'js/build/components/xp-flyup.js',
    category: 'js',
    status: 'prod',
    loc: 146,
    description: 'Module Xp Flyup',
    dependencies: ['state.js', 'timing.js'],
    path: 'js/build/components/xp-flyup.js',
  },
  {
    name: 'js/build/config/timing.js',
    category: 'js',
    status: 'prod',
    loc: 121,
    description: 'Module Timing',
    dependencies: [],
    path: 'js/build/config/timing.js',
  },
  {
    name: 'js/build/config.js',
    category: 'js',
    status: 'prod',
    loc: 260,
    description: 'Module Config',
    dependencies: [],
    path: 'js/build/config.js',
  },
  {
    name: 'js/build/data/adapter.js',
    category: 'js',
    status: 'prod',
    loc: 62,
    description: 'Module Adapter',
    dependencies: ['adapter.js', 'progress-client.js'],
    path: 'js/build/data/adapter.js',
  },
  {
    name: 'js/build/data/courses.js',
    category: 'js',
    status: 'prod',
    loc: 2346,
    description: 'Module Courses',
    dependencies: [],
    path: 'js/build/data/courses.js',
  },
  {
    name: 'js/build/data/formations-data.js',
    category: 'js',
    status: 'prod',
    loc: 456,
    description: 'Module Formations Data',
    dependencies: [],
    path: 'js/build/data/formations-data.js',
  },
  {
    name: 'js/build/data/skills-data.js',
    category: 'js',
    status: 'prod',
    loc: 421,
    description: 'Module Skills Data',
    dependencies: [],
    path: 'js/build/data/skills-data.js',
  },
  {
    name: 'js/build/data/skills.js',
    category: 'js',
    status: 'prod',
    loc: 1074,
    description: 'Module Skills',
    dependencies: [],
    path: 'js/build/data/skills.js',
  },
  {
    name: 'js/build/handlers.js',
    category: 'js',
    status: 'prod',
    loc: 345,
    description: 'Module Handlers',
    dependencies: ['config.js', 'state.js', 'adapter.js', 'modal.js', 'tree.js', 'dom.js'],
    path: 'js/build/handlers.js',
  },
  {
    name: 'js/build/index.js',
    category: 'js',
    status: 'prod',
    loc: 555,
    description: 'Module Index',
    dependencies: [
      'config.js',
      'state.js',
      'adapter.js',
      'modal.js',
      'tree.js',
      'intro.js',
      'quiz.js',
      'tracks.js',
      'project-panel.js',
      'factory-panel.js',
      'formation-panel.js',
      'builder-profile.js',
      'skill-tree-view.js',
      'github-timeline.js',
      'feature-tooltip.js',
      'onboarding-progress.js',
      'streak-counter.js',
      'xp-flyup.js',
      'share-button.js',
      'index.js',
      'animations.js',
      'handlers.js',
      'security.js',
      'dom.js',
      'timing.js',
    ],
    path: 'js/build/index.js',
  },
  {
    name: 'js/build/progress-tracker.js',
    category: 'js',
    status: 'prod',
    loc: 673,
    description: 'Module Progress Tracker',
    dependencies: [],
    path: 'js/build/progress-tracker.js',
  },
  {
    name: 'js/build/renderer/animations.js',
    category: 'js',
    status: 'prod',
    loc: 582,
    description: 'Module Animations',
    dependencies: ['state.js', 'phi.js'],
    path: 'js/build/renderer/animations.js',
  },
  {
    name: 'js/build/renderer/camera/camera-controller.js',
    category: 'js',
    status: 'prod',
    loc: 522,
    description: 'Module Camera Controller',
    dependencies: [],
    path: 'js/build/renderer/camera/camera-controller.js',
  },
  {
    name: 'js/build/renderer/effects/custom-shaders.js',
    category: 'js',
    status: 'prod',
    loc: 348,
    description: 'Module Custom Shaders',
    dependencies: [],
    path: 'js/build/renderer/effects/custom-shaders.js',
  },
  {
    name: 'js/build/renderer/effects/fire-particles.js',
    category: 'js',
    status: 'prod',
    loc: 282,
    description: 'Module Fire Particles',
    dependencies: [],
    path: 'js/build/renderer/effects/fire-particles.js',
  },
  {
    name: 'js/build/renderer/effects/post-processing.js',
    category: 'js',
    status: 'prod',
    loc: 385,
    description: 'Module Post Processing',
    dependencies: [],
    path: 'js/build/renderer/effects/post-processing.js',
  },
  {
    name: 'js/build/renderer/effects/snow-particles.js',
    category: 'js',
    status: 'prod',
    loc: 283,
    description: 'Module Snow Particles',
    dependencies: [],
    path: 'js/build/renderer/effects/snow-particles.js',
  },
  {
    name: 'js/build/renderer/index.js',
    category: 'js',
    status: 'prod',
    loc: 342,
    description: 'Module Index',
    dependencies: ['state.js'],
    path: 'js/build/renderer/index.js',
  },
  {
    name: 'js/build/renderer/objects/burn-core.js',
    category: 'js',
    status: 'prod',
    loc: 326,
    description: 'Module Burn Core',
    dependencies: [],
    path: 'js/build/renderer/objects/burn-core.js',
  },
  {
    name: 'js/build/renderer/objects/skill-node.js',
    category: 'js',
    status: 'prod',
    loc: 370,
    description: 'Module Skill Node',
    dependencies: ['phi.js'],
    path: 'js/build/renderer/objects/skill-node.js',
  },
  {
    name: 'js/build/renderer/objects/stone-island.js',
    category: 'js',
    status: 'prod',
    loc: 379,
    description: 'Module Stone Island',
    dependencies: [],
    path: 'js/build/renderer/objects/stone-island.js',
  },
  {
    name: 'js/build/renderer/objects/yggdrasil-tree.js',
    category: 'js',
    status: 'prod',
    loc: 331,
    description: 'Module Yggdrasil Tree',
    dependencies: [],
    path: 'js/build/renderer/objects/yggdrasil-tree.js',
  },
  {
    name: 'js/build/renderer/performance.js',
    category: 'js',
    status: 'prod',
    loc: 451,
    description: 'Module Performance',
    dependencies: [],
    path: 'js/build/renderer/performance.js',
  },
  {
    name: 'js/build/renderer/scenes/project-tree.js',
    category: 'js',
    status: 'prod',
    loc: 396,
    description: 'Module Project Tree',
    dependencies: ['state.js', 'adapter.js', 'skill-node.js', 'phi.js'],
    path: 'js/build/renderer/scenes/project-tree.js',
  },
  {
    name: 'js/build/renderer/svg-renderer.js',
    category: 'js',
    status: 'prod',
    loc: 379,
    description: 'Module Svg Renderer',
    dependencies: ['state.js', 'tree.js', 'dom.js', 'timing.js'],
    path: 'js/build/renderer/svg-renderer.js',
  },
  {
    name: 'js/build/renderer/three-renderer.js',
    category: 'js',
    status: 'prod',
    loc: 939,
    description: 'Module Three Renderer',
    dependencies: [
      'state.js',
      'adapter.js',
      'phi.js',
      'fire-particles.js',
      'snow-particles.js',
      'yggdrasil-tree.js',
      'stone-island.js',
      'burn-core.js',
      'camera-controller.js',
      'post-processing.js',
      'performance.js',
      'project-tree.js',
    ],
    path: 'js/build/renderer/three-renderer.js',
  },
  {
    name: 'js/build/services/burn-api.js',
    category: 'js',
    status: 'prod',
    loc: 180,
    description: 'Module Burn Api',
    dependencies: [],
    path: 'js/build/services/burn-api.js',
  },
  {
    name: 'js/build/services/github-api.js',
    category: 'js',
    status: 'prod',
    loc: 579,
    description: 'Module Github Api',
    dependencies: [],
    path: 'js/build/services/github-api.js',
  },
  {
    name: 'js/build/services/solana-client.js',
    category: 'js',
    status: 'prod',
    loc: 344,
    description: 'Module Solana Client',
    dependencies: [],
    path: 'js/build/services/solana-client.js',
  },
  {
    name: 'js/build/state/event-bus.js',
    category: 'js',
    status: 'prod',
    loc: 120,
    description: 'Module Event Bus',
    dependencies: [],
    path: 'js/build/state/event-bus.js',
  },
  {
    name: 'js/build/state/index.js',
    category: 'js',
    status: 'prod',
    loc: 12,
    description: 'Module Index',
    dependencies: [
      'event-bus.js',
      'state-machine.js',
      'onboarding-manager.js',
      'quiz-manager.js',
      'persistence-manager.js',
    ],
    path: 'js/build/state/index.js',
  },
  {
    name: 'js/build/state/onboarding-manager.js',
    category: 'js',
    status: 'prod',
    loc: 153,
    description: 'Module Onboarding Manager',
    dependencies: ['event-bus.js'],
    path: 'js/build/state/onboarding-manager.js',
  },
  {
    name: 'js/build/state/persistence-manager.js',
    category: 'js',
    status: 'prod',
    loc: 166,
    description: 'Module Persistence Manager',
    dependencies: ['config.js'],
    path: 'js/build/state/persistence-manager.js',
  },
  {
    name: 'js/build/state/quiz-manager.js',
    category: 'js',
    status: 'prod',
    loc: 156,
    description: 'Module Quiz Manager',
    dependencies: ['config.js', 'event-bus.js'],
    path: 'js/build/state/quiz-manager.js',
  },
  {
    name: 'js/build/state/state-machine.js',
    category: 'js',
    status: 'prod',
    loc: 161,
    description: 'Module State Machine',
    dependencies: ['config.js', 'event-bus.js'],
    path: 'js/build/state/state-machine.js',
  },
  {
    name: 'js/build/state.js',
    category: 'js',
    status: 'prod',
    loc: 383,
    description: 'Module State',
    dependencies: [
      'config.js',
      'event-bus.js',
      'state-machine.js',
      'onboarding-manager.js',
      'quiz-manager.js',
      'persistence-manager.js',
    ],
    path: 'js/build/state.js',
  },
  {
    name: 'js/build/utils/dom.js',
    category: 'js',
    status: 'prod',
    loc: 394,
    description: 'Module Dom',
    dependencies: ['security.js'],
    path: 'js/build/utils/dom.js',
  },
  {
    name: 'js/build/utils/phi.js',
    category: 'js',
    status: 'prod',
    loc: 273,
    description: 'Module Phi',
    dependencies: [],
    path: 'js/build/utils/phi.js',
  },
  {
    name: 'js/build/utils/security.js',
    category: 'js',
    status: 'prod',
    loc: 321,
    description: 'Module Security',
    dependencies: [],
    path: 'js/build/utils/security.js',
  },
  {
    name: 'js/build/yggdrasil-mock-data.js',
    category: 'js',
    status: 'prod',
    loc: 449,
    description: 'Module Yggdrasil Mock Data',
    dependencies: [],
    path: 'js/build/yggdrasil-mock-data.js',
  },
  {
    name: 'js/build/yggdrasil-quiz.js',
    category: 'js',
    status: 'prod',
    loc: 188,
    description: 'Module Yggdrasil Quiz',
    dependencies: [],
    path: 'js/build/yggdrasil-quiz.js',
  },
  {
    name: 'js/build/yggdrasil-unified.js',
    category: 'js',
    status: 'prod',
    loc: 2429,
    description: 'Module Yggdrasil Unified',
    dependencies: [
      'index.js',
      'courses.js',
      'skills.js',
      'progress-tracker.js',
      'timing.js',
      'adapter.js',
      'burn-api.js',
      'yggdrasil-quiz.js',
      'yggdrasil-mock-data.js',
    ],
    path: 'js/build/yggdrasil-unified.js',
  },
  {
    name: 'js/burns.js',
    category: 'js',
    status: 'prod',
    loc: 278,
    description: 'Module Burns',
    dependencies: ['interactions.js', 'contextual-animations.js', 'audio-feedback.js'],
    path: 'js/burns.js',
  },
  {
    name: 'js/consent/index.js',
    category: 'js',
    status: 'prod',
    loc: 332,
    description: 'Module Index',
    dependencies: [],
    path: 'js/consent/index.js',
  },
  {
    name: 'js/core/config.js',
    category: 'js',
    status: 'prod',
    loc: 283,
    description: 'Module Config',
    dependencies: ['config.js'],
    path: 'js/core/config.js',
  },
  {
    name: 'js/core/debug.js',
    category: 'js',
    status: 'prod',
    loc: 184,
    description: 'Module Debug',
    dependencies: ['debug.js'],
    path: 'js/core/debug.js',
  },
  {
    name: 'js/core/errors.js',
    category: 'js',
    status: 'prod',
    loc: 506,
    description: 'Module Errors',
    dependencies: ['errors.js'],
    path: 'js/core/errors.js',
  },
  {
    name: 'js/core/event-bus.js',
    category: 'js',
    status: 'prod',
    loc: 262,
    description: 'Module Event Bus',
    dependencies: ['event-bus.js'],
    path: 'js/core/event-bus.js',
  },
  {
    name: 'js/core/index.js',
    category: 'js',
    status: 'prod',
    loc: 85,
    description: 'Module Index',
    dependencies: [
      'index.js',
      'event-bus.js',
      'errors.js',
      'config.js',
      'debug.js',
      'redis-client.js',
    ],
    path: 'js/core/index.js',
  },
  {
    name: 'js/core/redis-client.js',
    category: 'js',
    status: 'prod',
    loc: 512,
    description: 'Module Redis Client',
    dependencies: ['redis-client.js', 'event-bus.js', 'config.js', 'errors.js'],
    path: 'js/core/redis-client.js',
  },
  {
    name: 'js/dashboard/config.js',
    category: 'js',
    status: 'prod',
    loc: 522,
    description: 'Module Config',
    dependencies: [],
    path: 'js/dashboard/config.js',
  },
  {
    name: 'js/dashboard/data/adapter.js',
    category: 'js',
    status: 'prod',
    loc: 13,
    description: 'Module Adapter',
    dependencies: ['adapter.js', 'progress-client.js'],
    path: 'js/dashboard/data/adapter.js',
  },
  {
    name: 'js/dashboard/data/cynic-bridge.js',
    category: 'js',
    status: 'prod',
    loc: 218,
    description: 'Module Cynic Bridge',
    dependencies: [],
    path: 'js/dashboard/data/cynic-bridge.js',
  },
  {
    name: 'js/dashboard/data/formations.js',
    category: 'js',
    status: 'prod',
    loc: 23,
    description: 'Module Formations',
    dependencies: ['formations.js'],
    path: 'js/dashboard/data/formations.js',
  },
  {
    name: 'js/dashboard/index.js',
    category: 'js',
    status: 'prod',
    loc: 284,
    description: 'Module Index',
    dependencies: [
      'config.js',
      'yggdrasil.js',
      'tooltip.js',
      'panel.js',
      'formation-panel.js',
      'error-boundary.js',
      'onboarding.js',
    ],
    path: 'js/dashboard/index.js',
  },
  {
    name: 'js/dashboard/tree/camera.js',
    category: 'js',
    status: 'prod',
    loc: 392,
    description: 'Module Camera',
    dependencies: ['config.js'],
    path: 'js/dashboard/tree/camera.js',
  },
  {
    name: 'js/dashboard/tree/input-controller.js',
    category: 'js',
    status: 'prod',
    loc: 393,
    description: 'Module Input Controller',
    dependencies: ['config.js'],
    path: 'js/dashboard/tree/input-controller.js',
  },
  {
    name: 'js/dashboard/tree/island-factory.js',
    category: 'js',
    status: 'prod',
    loc: 251,
    description: 'Module Island Factory',
    dependencies: ['config.js', 'particles.js'],
    path: 'js/dashboard/tree/island-factory.js',
  },
  {
    name: 'js/dashboard/tree/nodes.js',
    category: 'js',
    status: 'prod',
    loc: 219,
    description: 'Module Nodes',
    dependencies: ['config.js'],
    path: 'js/dashboard/tree/nodes.js',
  },
  {
    name: 'js/dashboard/tree/particles.js',
    category: 'js',
    status: 'prod',
    loc: 484,
    description: 'Module Particles',
    dependencies: ['config.js'],
    path: 'js/dashboard/tree/particles.js',
  },
  {
    name: 'js/dashboard/tree/skills.js',
    category: 'js',
    status: 'prod',
    loc: 575,
    description: 'Module Skills',
    dependencies: ['config.js'],
    path: 'js/dashboard/tree/skills.js',
  },
  {
    name: 'js/dashboard/tree/yggdrasil.js',
    category: 'js',
    status: 'prod',
    loc: 638,
    description: 'Module Yggdrasil',
    dependencies: [
      'config.js',
      'particles.js',
      'camera.js',
      'skills.js',
      'input-controller.js',
      'island-factory.js',
    ],
    path: 'js/dashboard/tree/yggdrasil.js',
  },
  {
    name: 'js/dashboard/ui/error-boundary.js',
    category: 'js',
    status: 'prod',
    loc: 208,
    description: 'Module Error Boundary',
    dependencies: [],
    path: 'js/dashboard/ui/error-boundary.js',
  },
  {
    name: 'js/dashboard/ui/formation-panel.js',
    category: 'js',
    status: 'prod',
    loc: 361,
    description: 'Module Formation Panel',
    dependencies: ['formations.js'],
    path: 'js/dashboard/ui/formation-panel.js',
  },
  {
    name: 'js/dashboard/ui/onboarding.js',
    category: 'js',
    status: 'prod',
    loc: 338,
    description: 'Module Onboarding',
    dependencies: [],
    path: 'js/dashboard/ui/onboarding.js',
  },
  {
    name: 'js/dashboard/ui/panel.js',
    category: 'js',
    status: 'prod',
    loc: 169,
    description: 'Module Panel',
    dependencies: [],
    path: 'js/dashboard/ui/panel.js',
  },
  {
    name: 'js/dashboard/ui/tooltip.js',
    category: 'js',
    status: 'prod',
    loc: 207,
    description: 'Module Tooltip',
    dependencies: [],
    path: 'js/dashboard/ui/tooltip.js',
  },
  {
    name: 'js/debug.js',
    category: 'js',
    status: 'prod',
    loc: 45,
    description: 'Module Debug',
    dependencies: ['debug.js'],
    path: 'js/debug.js',
  },
  {
    name: 'js/deep-learn.js',
    category: 'js',
    status: 'prod',
    loc: 130,
    description: 'Module Deep Learn',
    dependencies: [],
    path: 'js/deep-learn.js',
  },
  {
    name: 'js/ecosystem.js',
    category: 'js',
    status: 'prod',
    loc: 556,
    description: 'ASDF Ecosystem Shell — nav drawer, themes, density',
    dependencies: [],
    path: 'js/ecosystem.js',
  },
  {
    name: 'js/forecast.js',
    category: 'js',
    status: 'prod',
    loc: 335,
    description: 'Module Forecast',
    dependencies: [],
    path: 'js/forecast.js',
  },
  {
    name: 'js/holdex.js',
    category: 'js',
    status: 'prod',
    loc: 277,
    description: 'Module Holdex',
    dependencies: [],
    path: 'js/holdex.js',
  },
  {
    name: 'js/hub-majestic.js',
    category: 'js',
    status: 'prod',
    loc: 257,
    description: 'Landing page — particle effects et interactions',
    dependencies: ['interactions.js'],
    path: 'js/hub-majestic.js',
  },
  {
    name: 'js/ignition.js',
    category: 'js',
    status: 'dev',
    loc: 279,
    description: 'Module Ignition',
    dependencies: [],
    path: 'js/ignition.js',
  },
  {
    name: 'js/journey-data.js',
    category: 'js',
    status: 'prod',
    loc: 562,
    description: 'Module Journey Data',
    dependencies: [],
    path: 'js/journey-data.js',
  },
  {
    name: 'js/journey-progress.js',
    category: 'js',
    status: 'prod',
    loc: 328,
    description: 'Module Journey Progress',
    dependencies: [],
    path: 'js/journey-progress.js',
  },
  {
    name: 'js/journey.js',
    category: 'js',
    status: 'prod',
    loc: 559,
    description: 'Module Journey',
    dependencies: [],
    path: 'js/journey.js',
  },
  {
    name: 'js/learn-build/components/dashboard.js',
    category: 'js',
    status: 'prod',
    loc: 349,
    description: 'Module Dashboard',
    dependencies: ['index.js', 'ui-controller.js'],
    path: 'js/learn-build/components/dashboard.js',
  },
  {
    name: 'js/learn-build/index.js',
    category: 'js',
    status: 'prod',
    loc: 385,
    description: 'Module Index',
    dependencies: ['index.js', 'event-bus.js', 'debug.js', 'quests.js', 'modules.js'],
    path: 'js/learn-build/index.js',
  },
  {
    name: 'js/learn-build/modules.js',
    category: 'js',
    status: 'prod',
    loc: 517,
    description: 'Module Modules',
    dependencies: ['index.js'],
    path: 'js/learn-build/modules.js',
  },
  {
    name: 'js/learn-build/quests.js',
    category: 'js',
    status: 'prod',
    loc: 418,
    description: 'Module Quests',
    dependencies: [],
    path: 'js/learn-build/quests.js',
  },
  {
    name: 'js/learn-build/ui-controller.js',
    category: 'js',
    status: 'prod',
    loc: 447,
    description: 'Module Ui Controller',
    dependencies: ['index.js', 'event-bus.js', 'debug.js'],
    path: 'js/learn-build/ui-controller.js',
  },
  {
    name: 'js/learn.js',
    category: 'js',
    status: 'prod',
    loc: 335,
    description: 'Module Learn',
    dependencies: [],
    path: 'js/learn.js',
  },
  {
    name: 'js/me.js',
    category: 'js',
    status: 'prod',
    loc: 283,
    description: 'Module Me',
    dependencies: [
      'achievements.js',
      'progressive-disclosure.js',
      'sound-system.js',
      'interactions.js',
      'easter-eggs.js',
    ],
    path: 'js/me.js',
  },
  {
    name: 'js/persistence/index.js',
    category: 'js',
    status: 'prod',
    loc: 16,
    description: 'Module Index',
    dependencies: ['index.js', 'sync.js'],
    path: 'js/persistence/index.js',
  },
  {
    name: 'js/persistence/sync.js',
    category: 'js',
    status: 'prod',
    loc: 363,
    description: 'Module Sync',
    dependencies: ['sync.js', 'redis-client.js', 'event-bus.js', 'debug.js'],
    path: 'js/persistence/sync.js',
  },
  {
    name: 'js/realtime/client.js',
    category: 'js',
    status: 'prod',
    loc: 631,
    description: 'Module Client',
    dependencies: ['event-bus.js'],
    path: 'js/realtime/client.js',
  },
  {
    name: 'js/realtime/index.js',
    category: 'js',
    status: 'prod',
    loc: 65,
    description: 'Module Index',
    dependencies: ['index.js', 'client.js'],
    path: 'js/realtime/index.js',
  },
  {
    name: 'js/shared/data/adapter.js',
    category: 'js',
    status: 'prod',
    loc: 332,
    description: 'Module Adapter',
    dependencies: ['formations.js', 'progress-client.js'],
    path: 'js/shared/data/adapter.js',
  },
  {
    name: 'js/shared/data/formations.js',
    category: 'js',
    status: 'prod',
    loc: 502,
    description: 'Module Formations',
    dependencies: ['formations.js'],
    path: 'js/shared/data/formations.js',
  },
  {
    name: 'js/shared/data/index.js',
    category: 'js',
    status: 'prod',
    loc: 31,
    description: 'Module Index',
    dependencies: ['index.js', 'formations.js', 'adapter.js', 'progress-client.js'],
    path: 'js/shared/data/index.js',
  },
  {
    name: 'js/shared/data/progress-client.js',
    category: 'js',
    status: 'prod',
    loc: 418,
    description: 'Module Progress Client',
    dependencies: ['formations.js'],
    path: 'js/shared/data/progress-client.js',
  },
  {
    name: 'js/shared/security.js',
    category: 'js',
    status: 'prod',
    loc: 31,
    description: 'Module Security',
    dependencies: [],
    path: 'js/shared/security.js',
  },
  {
    name: 'js/solana/index.js',
    category: 'js',
    status: 'prod',
    loc: 296,
    description: 'Module Index',
    dependencies: ['client.js', 'wallet-manager.js', 'transactions.js', 'adapter.js'],
    path: 'js/solana/index.js',
  },
  {
    name: 'js/solana/kit/client.js',
    category: 'js',
    status: 'prod',
    loc: 265,
    description: 'Module Client',
    dependencies: [],
    path: 'js/solana/kit/client.js',
  },
  {
    name: 'js/solana/kit/transactions.js',
    category: 'js',
    status: 'prod',
    loc: 271,
    description: 'Module Transactions',
    dependencies: ['client.js', 'wallet-manager.js'],
    path: 'js/solana/kit/transactions.js',
  },
  {
    name: 'js/solana/kit/wallet-manager.js',
    category: 'js',
    status: 'prod',
    loc: 411,
    description: 'Module Wallet Manager',
    dependencies: [],
    path: 'js/solana/kit/wallet-manager.js',
  },
  {
    name: 'js/solana/wallet-standard.js',
    category: 'js',
    status: 'prod',
    loc: 299,
    description: 'Module Wallet Standard',
    dependencies: [],
    path: 'js/solana/wallet-standard.js',
  },
  {
    name: 'js/solana/web3-compat/adapter.js',
    category: 'js',
    status: 'prod',
    loc: 208,
    description: 'Module Adapter',
    dependencies: ['client.js', 'wallet-manager.js', 'transactions.js'],
    path: 'js/solana/web3-compat/adapter.js',
  },
  {
    name: 'js/staking.js',
    category: 'js',
    status: 'prod',
    loc: 356,
    description: 'Module Staking',
    dependencies: ['interactions.js', 'contextual-animations.js', 'audio-feedback.js'],
    path: 'js/staking.js',
  },
  {
    name: 'js/terrier.js',
    category: 'js',
    status: 'prod',
    loc: 33,
    description: 'Module Terrier',
    dependencies: [],
    path: 'js/terrier.js',
  },
  {
    name: 'js/ui/index.js',
    category: 'js',
    status: 'prod',
    loc: 66,
    description: 'Module Index',
    dependencies: ['toast.js', 'modal.js', 'index.js'],
    path: 'js/ui/index.js',
  },
  {
    name: 'js/ui/modal.js',
    category: 'js',
    status: 'prod',
    loc: 643,
    description: 'Module Modal',
    dependencies: ['modal.js', 'event-bus.js', 'engine.js'],
    path: 'js/ui/modal.js',
  },
  {
    name: 'js/ui/toast.js',
    category: 'js',
    status: 'prod',
    loc: 560,
    description: 'Module Toast',
    dependencies: ['toast.js', 'event-bus.js', 'engine.js'],
    path: 'js/ui/toast.js',
  },
  {
    name: 'js/utils/achievements.js',
    category: 'js',
    status: 'prod',
    loc: 620,
    description: 'Module Achievements',
    dependencies: ['achievements.js', 'sound-system.js', 'contextual-animations.js'],
    path: 'js/utils/achievements.js',
  },
  {
    name: 'js/utils/audio-feedback.js',
    category: 'js',
    status: 'prod',
    loc: 352,
    description: 'Module Audio Feedback',
    dependencies: ['audio-feedback.js'],
    path: 'js/utils/audio-feedback.js',
  },
  {
    name: 'js/utils/contextual-animations.js',
    category: 'js',
    status: 'prod',
    loc: 436,
    description: 'Module Contextual Animations',
    dependencies: ['contextual-animations.js', 'interactions.js'],
    path: 'js/utils/contextual-animations.js',
  },
  {
    name: 'js/utils/easter-eggs.js',
    category: 'js',
    status: 'prod',
    loc: 496,
    description: 'Module Easter Eggs',
    dependencies: ['easter-eggs.js', 'sound-system.js', 'contextual-animations.js'],
    path: 'js/utils/easter-eggs.js',
  },
  {
    name: 'js/utils/interactions.js',
    category: 'js',
    status: 'prod',
    loc: 229,
    description: 'Module Interactions',
    dependencies: ['interactions.js'],
    path: 'js/utils/interactions.js',
  },
  {
    name: 'js/utils/progressive-disclosure.js',
    category: 'js',
    status: 'prod',
    loc: 492,
    description: 'Module Progressive Disclosure',
    dependencies: ['progressive-disclosure.js', 'sound-system.js'],
    path: 'js/utils/progressive-disclosure.js',
  },
  {
    name: 'js/utils/sound-system.js',
    category: 'js',
    status: 'prod',
    loc: 408,
    description: 'Module Sound System',
    dependencies: ['sound-system.js'],
    path: 'js/utils/sound-system.js',
  },
  {
    name: 'js/_archive_build.js',
    category: 'js',
    status: 'prod',
    loc: 2798,
    description: 'Module  Archive Build',
    dependencies: [],
    path: 'js/_archive_build.js',
  },
  {
    name: 'js/games/api.js',
    category: 'games',
    status: 'prod',
    loc: 219,
    description: 'Module jeu Api',
    dependencies: [],
    path: 'js/games/api.js',
  },
  {
    name: 'js/games/arcade-hub.js',
    category: 'games',
    status: 'prod',
    loc: 42,
    description: 'Module jeu Arcade Hub',
    dependencies: [],
    path: 'js/games/arcade-hub.js',
  },
  {
    name: 'js/games/asdf.js',
    category: 'games',
    status: 'prod',
    loc: 369,
    description: 'Module jeu Asdf',
    dependencies: [],
    path: 'js/games/asdf.js',
  },
  {
    name: 'js/games/avatar.js',
    category: 'games',
    status: 'prod',
    loc: 418,
    description: 'Module jeu Avatar',
    dependencies: [],
    path: 'js/games/avatar.js',
  },
  {
    name: 'js/games/challenges/index.js',
    category: 'games',
    status: 'prod',
    loc: 257,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/challenges/index.js',
  },
  {
    name: 'js/games/config.js',
    category: 'games',
    status: 'prod',
    loc: 247,
    description: 'Module jeu Config',
    dependencies: [],
    path: 'js/games/config.js',
  },
  {
    name: 'js/games/core/bootstrap.js',
    category: 'games',
    status: 'prod',
    loc: 253,
    description: 'Module jeu Bootstrap',
    dependencies: [],
    path: 'js/games/core/bootstrap.js',
  },
  {
    name: 'js/games/core/container.js',
    category: 'games',
    status: 'prod',
    loc: 150,
    description: 'Module jeu Container',
    dependencies: [],
    path: 'js/games/core/container.js',
  },
  {
    name: 'js/games/core/facades.js',
    category: 'games',
    status: 'prod',
    loc: 148,
    description: 'Module jeu Facades',
    dependencies: [],
    path: 'js/games/core/facades.js',
  },
  {
    name: 'js/games/cosmetics-btn.js',
    category: 'games',
    status: 'prod',
    loc: 25,
    description: 'Module jeu Cosmetics Btn',
    dependencies: [],
    path: 'js/games/cosmetics-btn.js',
  },
  {
    name: 'js/games/engage.js',
    category: 'games',
    status: 'prod',
    loc: 471,
    description: 'Module jeu Engage',
    dependencies: [],
    path: 'js/games/engage.js',
  },
  {
    name: 'js/games/engine.js',
    category: 'games',
    status: 'prod',
    loc: 60,
    description: 'Module jeu Engine',
    dependencies: [],
    path: 'js/games/engine.js',
  },
  {
    name: 'js/games/engines/BaseEngine.js',
    category: 'games',
    status: 'prod',
    loc: 342,
    description: 'Module jeu BaseEngine',
    dependencies: ['app.js', 'assets.js'],
    path: 'js/games/engines/BaseEngine.js',
  },
  {
    name: 'js/games/engines/burnorhold.js',
    category: 'games',
    status: 'prod',
    loc: 1008,
    description: 'Module jeu Burnorhold',
    dependencies: [],
    path: 'js/games/engines/burnorhold.js',
  },
  {
    name: 'js/games/engines/burnrunner.js',
    category: 'games',
    status: 'prod',
    loc: 1087,
    description: 'Module jeu Burnrunner',
    dependencies: [],
    path: 'js/games/engines/burnrunner.js',
  },
  {
    name: 'js/games/engines/cryptoheist.js',
    category: 'games',
    status: 'prod',
    loc: 921,
    description: 'Module jeu Cryptoheist',
    dependencies: [],
    path: 'js/games/engines/cryptoheist.js',
  },
  {
    name: 'js/games/engines/dexdash.js',
    category: 'games',
    status: 'prod',
    loc: 854,
    description: 'Module jeu Dexdash',
    dependencies: [],
    path: 'js/games/engines/dexdash.js',
  },
  {
    name: 'js/games/engines/index.js',
    category: 'games',
    status: 'prod',
    loc: 213,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/engines/index.js',
  },
  {
    name: 'js/games/engines/liquiditymaze.js',
    category: 'games',
    status: 'prod',
    loc: 1041,
    description: 'Module jeu Liquiditymaze',
    dependencies: [],
    path: 'js/games/engines/liquiditymaze.js',
  },
  {
    name: 'js/games/engines/pumparena.js',
    category: 'games',
    status: 'prod',
    loc: 2794,
    description: 'Module jeu Pumparena',
    dependencies: [],
    path: 'js/games/engines/pumparena.js',
  },
  {
    name: 'js/games/engines/scamblaster.js',
    category: 'games',
    status: 'prod',
    loc: 813,
    description: 'Module jeu Scamblaster',
    dependencies: [],
    path: 'js/games/engines/scamblaster.js',
  },
  {
    name: 'js/games/engines/stakestacker.js',
    category: 'games',
    status: 'prod',
    loc: 560,
    description: 'Module jeu Stakestacker',
    dependencies: [],
    path: 'js/games/engines/stakestacker.js',
  },
  {
    name: 'js/games/engines/tokencatcher.js',
    category: 'games',
    status: 'prod',
    loc: 1053,
    description: 'Module jeu Tokencatcher',
    dependencies: [],
    path: 'js/games/engines/tokencatcher.js',
  },
  {
    name: 'js/games/engines/whalewatch.js',
    category: 'games',
    status: 'prod',
    loc: 700,
    description: 'Module jeu Whalewatch',
    dependencies: [],
    path: 'js/games/engines/whalewatch.js',
  },
  {
    name: 'js/games/hub/audio.js',
    category: 'games',
    status: 'prod',
    loc: 466,
    description: 'Module jeu Audio',
    dependencies: [],
    path: 'js/games/hub/audio.js',
  },
  {
    name: 'js/games/hub/index.js',
    category: 'games',
    status: 'prod',
    loc: 284,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/hub/index.js',
  },
  {
    name: 'js/games/hub/profile.js',
    category: 'games',
    status: 'prod',
    loc: 749,
    description: 'Module jeu Profile',
    dependencies: [],
    path: 'js/games/hub/profile.js',
  },
  {
    name: 'js/games/hub/settings.js',
    category: 'games',
    status: 'prod',
    loc: 653,
    description: 'Module jeu Settings',
    dependencies: [],
    path: 'js/games/hub/settings.js',
  },
  {
    name: 'js/games/main.js',
    category: 'games',
    status: 'prod',
    loc: 205,
    description: 'Module jeu Main',
    dependencies: [],
    path: 'js/games/main.js',
  },
  {
    name: 'js/games/pixi/app.js',
    category: 'games',
    status: 'prod',
    loc: 154,
    description: 'Module jeu App',
    dependencies: [],
    path: 'js/games/pixi/app.js',
  },
  {
    name: 'js/games/pixi/assets.js',
    category: 'games',
    status: 'prod',
    loc: 131,
    description: 'Module jeu Assets',
    dependencies: [],
    path: 'js/games/pixi/assets.js',
  },
  {
    name: 'js/games/pixi/canvas-adapter.js',
    category: 'games',
    status: 'prod',
    loc: 337,
    description: 'Module jeu Canvas Adapter',
    dependencies: ['app.js'],
    path: 'js/games/pixi/canvas-adapter.js',
  },
  {
    name: 'js/games/pixi/index.js',
    category: 'games',
    status: 'prod',
    loc: 53,
    description: 'Module jeu Index',
    dependencies: ['index.js', 'app.js', 'assets.js', 'pools.js', 'canvas-adapter.js'],
    path: 'js/games/pixi/index.js',
  },
  {
    name: 'js/games/pixi/pools.js',
    category: 'games',
    status: 'prod',
    loc: 293,
    description: 'Module jeu Pools',
    dependencies: [],
    path: 'js/games/pixi/pools.js',
  },
  {
    name: 'js/games/rewards.js',
    category: 'games',
    status: 'prod',
    loc: 501,
    description: 'Module jeu Rewards',
    dependencies: [],
    path: 'js/games/rewards.js',
  },
  {
    name: 'js/games/shared/canvas.js',
    category: 'games',
    status: 'prod',
    loc: 116,
    description: 'Module jeu Canvas',
    dependencies: [],
    path: 'js/games/shared/canvas.js',
  },
  {
    name: 'js/games/shared/index.js',
    category: 'games',
    status: 'prod',
    loc: 85,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/shared/index.js',
  },
  {
    name: 'js/games/shared/input.js',
    category: 'games',
    status: 'prod',
    loc: 162,
    description: 'Module jeu Input',
    dependencies: [],
    path: 'js/games/shared/input.js',
  },
  {
    name: 'js/games/shared/intervals.js',
    category: 'games',
    status: 'prod',
    loc: 119,
    description: 'Module jeu Intervals',
    dependencies: [],
    path: 'js/games/shared/intervals.js',
  },
  {
    name: 'js/games/shared/juice.js',
    category: 'games',
    status: 'prod',
    loc: 669,
    description: 'Module jeu Juice',
    dependencies: [],
    path: 'js/games/shared/juice.js',
  },
  {
    name: 'js/games/shared/lifecycle.js',
    category: 'games',
    status: 'prod',
    loc: 243,
    description: 'Module jeu Lifecycle',
    dependencies: [],
    path: 'js/games/shared/lifecycle.js',
  },
  {
    name: 'js/games/shared/scoring.js',
    category: 'games',
    status: 'prod',
    loc: 70,
    description: 'Module jeu Scoring',
    dependencies: [],
    path: 'js/games/shared/scoring.js',
  },
  {
    name: 'js/games/shared/timing-config.js',
    category: 'games',
    status: 'prod',
    loc: 155,
    description: 'Module jeu Timing Config',
    dependencies: [],
    path: 'js/games/shared/timing-config.js',
  },
  {
    name: 'js/games/shared/timing.js',
    category: 'games',
    status: 'prod',
    loc: 112,
    description: 'Module jeu Timing',
    dependencies: [],
    path: 'js/games/shared/timing.js',
  },
  {
    name: 'js/games/shared/validation.js',
    category: 'games',
    status: 'prod',
    loc: 65,
    description: 'Module jeu Validation',
    dependencies: [],
    path: 'js/games/shared/validation.js',
  },
  {
    name: 'js/games/shop/canvas.js',
    category: 'games',
    status: 'prod',
    loc: 489,
    description: 'Module jeu Canvas',
    dependencies: [],
    path: 'js/games/shop/canvas.js',
  },
  {
    name: 'js/games/shop/catalog.js',
    category: 'games',
    status: 'prod',
    loc: 419,
    description: 'Module jeu Catalog',
    dependencies: [],
    path: 'js/games/shop/catalog.js',
  },
  {
    name: 'js/games/shop/collections.js',
    category: 'games',
    status: 'prod',
    loc: 324,
    description: 'Module jeu Collections',
    dependencies: [],
    path: 'js/games/shop/collections.js',
  },
  {
    name: 'js/games/shop/currency.js',
    category: 'games',
    status: 'prod',
    loc: 312,
    description: 'Module jeu Currency',
    dependencies: [],
    path: 'js/games/shop/currency.js',
  },
  {
    name: 'js/games/shop/favorites.js',
    category: 'games',
    status: 'prod',
    loc: 215,
    description: 'Module jeu Favorites',
    dependencies: [],
    path: 'js/games/shop/favorites.js',
  },
  {
    name: 'js/games/shop/filters.js',
    category: 'games',
    status: 'prod',
    loc: 491,
    description: 'Module jeu Filters',
    dependencies: [],
    path: 'js/games/shop/filters.js',
  },
  {
    name: 'js/games/shop/index.js',
    category: 'games',
    status: 'prod',
    loc: 515,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/shop/index.js',
  },
  {
    name: 'js/games/shop/itemCard.js',
    category: 'games',
    status: 'prod',
    loc: 341,
    description: 'Module jeu ItemCard',
    dependencies: [],
    path: 'js/games/shop/itemCard.js',
  },
  {
    name: 'js/games/shop/particles.js',
    category: 'games',
    status: 'prod',
    loc: 368,
    description: 'Module jeu Particles',
    dependencies: [],
    path: 'js/games/shop/particles.js',
  },
  {
    name: 'js/games/shop/placeholders.js',
    category: 'games',
    status: 'prod',
    loc: 439,
    description: 'Module jeu Placeholders',
    dependencies: [],
    path: 'js/games/shop/placeholders.js',
  },
  {
    name: 'js/games/shop/preview.js',
    category: 'games',
    status: 'prod',
    loc: 508,
    description: 'Module jeu Preview',
    dependencies: [],
    path: 'js/games/shop/preview.js',
  },
  {
    name: 'js/games/shop/purchase.js',
    category: 'games',
    status: 'prod',
    loc: 342,
    description: 'Module jeu Purchase',
    dependencies: [],
    path: 'js/games/shop/purchase.js',
  },
  {
    name: 'js/games/shop/state.js',
    category: 'games',
    status: 'prod',
    loc: 597,
    description: 'Module jeu State',
    dependencies: [],
    path: 'js/games/shop/state.js',
  },
  {
    name: 'js/games/shop/sync.js',
    category: 'games',
    status: 'prod',
    loc: 401,
    description: 'Module jeu Sync',
    dependencies: [],
    path: 'js/games/shop/sync.js',
  },
  {
    name: 'js/games/shop/toast.js',
    category: 'games',
    status: 'prod',
    loc: 349,
    description: 'Module jeu Toast',
    dependencies: [],
    path: 'js/games/shop/toast.js',
  },
  {
    name: 'js/games/shop/ui.js',
    category: 'games',
    status: 'prod',
    loc: 846,
    description: 'Module jeu Ui',
    dependencies: [],
    path: 'js/games/shop/ui.js',
  },
  {
    name: 'js/games/shop/utils.js',
    category: 'games',
    status: 'prod',
    loc: 197,
    description: 'Module jeu Utils',
    dependencies: [],
    path: 'js/games/shop/utils.js',
  },
  {
    name: 'js/games/shop.js',
    category: 'games',
    status: 'prod',
    loc: 558,
    description: 'Module jeu Shop',
    dependencies: [],
    path: 'js/games/shop.js',
  },
  {
    name: 'js/games/solana.js',
    category: 'games',
    status: 'prod',
    loc: 224,
    description: 'Module jeu Solana',
    dependencies: [],
    path: 'js/games/solana.js',
  },
  {
    name: 'js/games/state.js',
    category: 'games',
    status: 'prod',
    loc: 441,
    description: 'Module jeu State',
    dependencies: [],
    path: 'js/games/state.js',
  },
  {
    name: 'js/games/ui/competitive.js',
    category: 'games',
    status: 'prod',
    loc: 126,
    description: 'Module jeu Competitive',
    dependencies: [],
    path: 'js/games/ui/competitive.js',
  },
  {
    name: 'js/games/ui/grid.js',
    category: 'games',
    status: 'prod',
    loc: 45,
    description: 'Module jeu Grid',
    dependencies: [],
    path: 'js/games/ui/grid.js',
  },
  {
    name: 'js/games/ui/index.js',
    category: 'games',
    status: 'prod',
    loc: 76,
    description: 'Module jeu Index',
    dependencies: [],
    path: 'js/games/ui/index.js',
  },
  {
    name: 'js/games/ui/leaderboard.js',
    category: 'games',
    status: 'prod',
    loc: 209,
    description: 'Module jeu Leaderboard',
    dependencies: [],
    path: 'js/games/ui/leaderboard.js',
  },
  {
    name: 'js/games/ui/modal.js',
    category: 'games',
    status: 'prod',
    loc: 228,
    description: 'Module jeu Modal',
    dependencies: [],
    path: 'js/games/ui/modal.js',
  },
  {
    name: 'js/games/ui/rotation.js',
    category: 'games',
    status: 'prod',
    loc: 97,
    description: 'Module jeu Rotation',
    dependencies: [],
    path: 'js/games/ui/rotation.js',
  },
  {
    name: 'js/games/utils.js',
    category: 'games',
    status: 'prod',
    loc: 431,
    description: 'Module jeu Utils',
    dependencies: [],
    path: 'js/games/utils.js',
  },
  {
    name: 'api/index.js',
    category: 'api',
    status: 'prod',
    loc: 1072,
    description: 'Main Express server — GOD FILE (refactoring needed)',
    dependencies: [
      'auth',
      'helius',
      'shop',
      'shopV2',
      'leaderboard',
      'gameValidation',
      'security',
      'metrics',
      'database',
      'webhooks',
      'assets',
      'achievements',
      'challenges',
      'notifications',
      'transactions',
      'referrals',
      'eventBus',
      'cache',
      'queue',
      'analytics',
      'scheduler',
      'ratelimit',
      'validator',
      'featureflags',
      'audit',
      'circuitbreaker',
      'tracing',
      'healthcheck',
      'config',
      'shutdown',
      'versioning',
      'batching',
      'compression',
      'rpcFailover',
      'txMonitor',
      'priorityFee',
      'wsManager',
      'dataExport',
      'idempotency',
      'sessionManager',
      'openApiGenerator',
      'storage',
      'routes',
      'monitoring',
      'realtimeNotifications',
      'postgres',
      'wsBroadcast',
    ],
    path: 'api/index.js',
  },
  {
    name: 'api/routes/admin.js',
    category: 'api',
    status: 'prod',
    loc: 1145,
    description: 'Route Admin — endpoint handler',
    dependencies: [
      'helpers',
      'auth',
      'security',
      'metrics',
      'database',
      'leaderboard',
      'cache',
      'queue',
      'analytics',
      'scheduler',
      'ratelimit',
      'validator',
      'featureflags',
      'audit',
      'circuitbreaker',
      'tracing',
      'healthcheck',
      'config',
      'shutdown',
      'versioning',
      'batching',
      'compression',
      'rpcFailover',
      'wsManager',
      'storage',
      'monitoring',
    ],
    path: 'api/routes/admin.js',
  },
  {
    name: 'api/routes/auth.js',
    category: 'api',
    status: 'prod',
    loc: 142,
    description: 'Route Auth — endpoint handler',
    dependencies: ['auth', 'helius', 'shop', 'leaderboard', 'helpers'],
    path: 'api/routes/auth.js',
  },
  {
    name: 'api/routes/data.js',
    category: 'api',
    status: 'prod',
    loc: 197,
    description: 'Route Data — endpoint handler',
    dependencies: ['helpers', 'auth', 'dataExport', 'sessionManager', 'leaderboard'],
    path: 'api/routes/data.js',
  },
  {
    name: 'api/routes/ecosystem.js',
    category: 'api',
    status: 'prod',
    loc: 336,
    description: 'Route Ecosystem — endpoint handler',
    dependencies: ['helpers', 'helius', 'leaderboard', 'auth', 'index'],
    path: 'api/routes/ecosystem.js',
  },
  {
    name: 'api/routes/formations.js',
    category: 'api',
    status: 'prod',
    loc: 430,
    description: 'Route Formations — endpoint handler',
    dependencies: ['helpers', 'auth', 'helius', 'audit', 'progression'],
    path: 'api/routes/formations.js',
  },
  {
    name: 'api/routes/games.js',
    category: 'api',
    status: 'prod',
    loc: 668,
    description: 'Route Games — endpoint handler',
    dependencies: [
      'helpers',
      'gameValidation',
      'achievements',
      'challenges',
      'leaderboard',
      'helius',
      'auth',
      'security',
      'gameReplay',
      'antiCheat',
      'progression',
      'gameAnalytics',
    ],
    path: 'api/routes/games.js',
  },
  {
    name: 'api/routes/helius.js',
    category: 'api',
    status: 'prod',
    loc: 632,
    description: 'Route Helius — endpoint handler',
    dependencies: [
      'helpers',
      'auth',
      'security',
      'helius',
      'assets',
      'webhooks',
      'leaderboard',
      'achievements',
      'metrics',
      'heliusEnhanced',
      'tokenMetadata',
      'heliusMetrics',
    ],
    path: 'api/routes/helius.js',
  },
  {
    name: 'api/routes/helpers.js',
    category: 'api',
    status: 'prod',
    loc: 114,
    description: 'Route Helpers — endpoint handler',
    dependencies: [],
    path: 'api/routes/helpers.js',
  },
  {
    name: 'api/routes/index.js',
    category: 'api',
    status: 'prod',
    loc: 38,
    description: 'Route Index — endpoint handler',
    dependencies: [
      'probes',
      'auth',
      'shop',
      'ecosystem',
      'games',
      'admin',
      'helius',
      'notifications',
      'formations',
      'transactions',
      'data',
      'referrals',
      'misc',
    ],
    path: 'api/routes/index.js',
  },
  {
    name: 'api/routes/misc.js',
    category: 'api',
    status: 'prod',
    loc: 153,
    description: 'Route Misc — endpoint handler',
    dependencies: [
      'helpers',
      'auth',
      'metrics',
      'security',
      'achievements',
      'batching',
      'versioning',
      'openApiGenerator',
    ],
    path: 'api/routes/misc.js',
  },
  {
    name: 'api/routes/notifications.js',
    category: 'api',
    status: 'prod',
    loc: 511,
    description: 'Route Notifications — endpoint handler',
    dependencies: [
      'helpers',
      'auth',
      'security',
      'notifications',
      'leaderboard',
      'audit',
      'helius',
      'ratelimit',
      'realtimeNotifications',
      'notificationPreferences',
      'pushNotifications',
      'wsBroadcast',
    ],
    path: 'api/routes/notifications.js',
  },
  {
    name: 'api/routes/probes.js',
    category: 'api',
    status: 'prod',
    loc: 62,
    description: 'Route Probes — endpoint handler',
    dependencies: ['healthcheck'],
    path: 'api/routes/probes.js',
  },
  {
    name: 'api/routes/referrals.js',
    category: 'api',
    status: 'prod',
    loc: 121,
    description: 'Route Referrals — endpoint handler',
    dependencies: ['helpers', 'auth', 'referrals', 'leaderboard', 'eventBus'],
    path: 'api/routes/referrals.js',
  },
  {
    name: 'api/routes/shop.js',
    category: 'api',
    status: 'prod',
    loc: 426,
    description: 'Route Shop — endpoint handler',
    dependencies: ['helpers', 'shop', 'shopV2', 'helius', 'auth', 'postgres'],
    path: 'api/routes/shop.js',
  },
  {
    name: 'api/routes/transactions.js',
    category: 'api',
    status: 'prod',
    loc: 266,
    description: 'Route Transactions — endpoint handler',
    dependencies: [
      'helpers',
      'auth',
      'security',
      'helius',
      'transactions',
      'txMonitor',
      'priorityFee',
      'leaderboard',
    ],
    path: 'api/routes/transactions.js',
  },
  {
    name: 'api/serverless.js',
    category: 'api',
    status: 'prod',
    loc: 223,
    description: 'Module Serverless',
    dependencies: ['games.cjs'],
    path: 'api/serverless.js',
  },
  {
    name: 'api/services/achievements.js',
    category: 'api',
    status: 'prod',
    loc: 653,
    description: 'Service Achievements',
    dependencies: ['audit'],
    path: 'api/services/achievements.js',
  },
  {
    name: 'api/services/analytics.js',
    category: 'api',
    status: 'prod',
    loc: 639,
    description: 'Service Analytics',
    dependencies: ['audit'],
    path: 'api/services/analytics.js',
  },
  {
    name: 'api/services/antiCheat.js',
    category: 'api',
    status: 'prod',
    loc: 902,
    description: 'Service AntiCheat',
    dependencies: ['audit'],
    path: 'api/services/antiCheat.js',
  },
  {
    name: 'api/services/assets.js',
    category: 'api',
    status: 'prod',
    loc: 447,
    description: 'Service Assets',
    dependencies: ['audit'],
    path: 'api/services/assets.js',
  },
  {
    name: 'api/services/audit.js',
    category: 'api',
    status: 'prod',
    loc: 890,
    description: 'Service Audit',
    dependencies: [],
    path: 'api/services/audit.js',
  },
  {
    name: 'api/services/auth.js',
    category: 'api',
    status: 'prod',
    loc: 329,
    description: 'Service Auth',
    dependencies: ['helius'],
    path: 'api/services/auth.js',
  },
  {
    name: 'api/services/batching.js',
    category: 'api',
    status: 'prod',
    loc: 531,
    description: 'Service Batching',
    dependencies: ['audit'],
    path: 'api/services/batching.js',
  },
  {
    name: 'api/services/cache.js',
    category: 'api',
    status: 'prod',
    loc: 505,
    description: 'Service Cache',
    dependencies: ['audit'],
    path: 'api/services/cache.js',
  },
  {
    name: 'api/services/challenges.js',
    category: 'api',
    status: 'prod',
    loc: 391,
    description: 'Service Challenges',
    dependencies: [],
    path: 'api/services/challenges.js',
  },
  {
    name: 'api/services/circuitbreaker.js',
    category: 'api',
    status: 'prod',
    loc: 579,
    description: 'Service Circuitbreaker',
    dependencies: ['audit'],
    path: 'api/services/circuitbreaker.js',
  },
  {
    name: 'api/services/compression.js',
    category: 'api',
    status: 'prod',
    loc: 514,
    description: 'Service Compression',
    dependencies: [],
    path: 'api/services/compression.js',
  },
  {
    name: 'api/services/config.js',
    category: 'api',
    status: 'prod',
    loc: 606,
    description: 'Service Config',
    dependencies: ['audit'],
    path: 'api/services/config.js',
  },
  {
    name: 'api/services/cynic.js',
    category: 'api',
    status: 'prod',
    loc: 139,
    description: 'Service Cynic',
    dependencies: [],
    path: 'api/services/cynic.js',
  },
  {
    name: 'api/services/database.js',
    category: 'api',
    status: 'prod',
    loc: 435,
    description: 'Service Database',
    dependencies: ['audit'],
    path: 'api/services/database.js',
  },
  {
    name: 'api/services/dataExport.js',
    category: 'api',
    status: 'prod',
    loc: 914,
    description: 'Service DataExport',
    dependencies: [
      'audit',
      'txMonitor',
      'achievements',
      'shop',
      'notifications',
      'gameValidation',
      'referrals',
    ],
    path: 'api/services/dataExport.js',
  },
  {
    name: 'api/services/debug.js',
    category: 'api',
    status: 'prod',
    loc: 39,
    description: 'Service Debug',
    dependencies: ['debug'],
    path: 'api/services/debug.js',
  },
  {
    name: 'api/services/eventBus.js',
    category: 'api',
    status: 'prod',
    loc: 420,
    description: 'Service EventBus',
    dependencies: ['audit'],
    path: 'api/services/eventBus.js',
  },
  {
    name: 'api/services/featureflags.js',
    category: 'api',
    status: 'prod',
    loc: 769,
    description: 'Service Featureflags',
    dependencies: ['audit'],
    path: 'api/services/featureflags.js',
  },
  {
    name: 'api/services/gameAnalytics.js',
    category: 'api',
    status: 'prod',
    loc: 799,
    description: 'Service GameAnalytics',
    dependencies: [],
    path: 'api/services/gameAnalytics.js',
  },
  {
    name: 'api/services/gameReplay.js',
    category: 'api',
    status: 'prod',
    loc: 719,
    description: 'Service GameReplay',
    dependencies: ['audit'],
    path: 'api/services/gameReplay.js',
  },
  {
    name: 'api/services/gameValidation.js',
    category: 'api',
    status: 'prod',
    loc: 353,
    description: 'Service GameValidation',
    dependencies: ['audit'],
    path: 'api/services/gameValidation.js',
  },
  {
    name: 'api/services/healthcheck.js',
    category: 'api',
    status: 'prod',
    loc: 561,
    description: 'Service Healthcheck',
    dependencies: ['audit'],
    path: 'api/services/healthcheck.js',
  },
  {
    name: 'api/services/helius.js',
    category: 'api',
    status: 'prod',
    loc: 798,
    description: 'Helius RPC client (audit score: A-)',
    dependencies: [],
    path: 'api/services/helius.js',
  },
  {
    name: 'api/services/heliusEnhanced.js',
    category: 'api',
    status: 'prod',
    loc: 640,
    description: 'Service HeliusEnhanced',
    dependencies: ['audit'],
    path: 'api/services/heliusEnhanced.js',
  },
  {
    name: 'api/services/heliusMetrics.js',
    category: 'api',
    status: 'prod',
    loc: 622,
    description: 'Service HeliusMetrics',
    dependencies: [],
    path: 'api/services/heliusMetrics.js',
  },
  {
    name: 'api/services/heliusRateLimiter.js',
    category: 'api',
    status: 'prod',
    loc: 596,
    description: 'Service HeliusRateLimiter',
    dependencies: ['audit'],
    path: 'api/services/heliusRateLimiter.js',
  },
  {
    name: 'api/services/heliusWebhooks.js',
    category: 'api',
    status: 'prod',
    loc: 531,
    description: 'Service HeliusWebhooks',
    dependencies: ['storage', 'monitoring'],
    path: 'api/services/heliusWebhooks.js',
  },
  {
    name: 'api/services/heliusWebSocket.js',
    category: 'api',
    status: 'prod',
    loc: 557,
    description: 'Service HeliusWebSocket',
    dependencies: ['audit'],
    path: 'api/services/heliusWebSocket.js',
  },
  {
    name: 'api/services/idempotency.js',
    category: 'api',
    status: 'prod',
    loc: 345,
    description: 'Service Idempotency',
    dependencies: [],
    path: 'api/services/idempotency.js',
  },
  {
    name: 'api/services/leaderboard.js',
    category: 'api',
    status: 'prod',
    loc: 348,
    description: 'Service Leaderboard',
    dependencies: ['helius', 'audit'],
    path: 'api/services/leaderboard.js',
  },
  {
    name: 'api/services/metrics.js',
    category: 'api',
    status: 'prod',
    loc: 319,
    description: 'Service Metrics',
    dependencies: [],
    path: 'api/services/metrics.js',
  },
  {
    name: 'api/services/monitoring.js',
    category: 'api',
    status: 'prod',
    loc: 314,
    description: 'Service Monitoring',
    dependencies: ['storage', 'postgres'],
    path: 'api/services/monitoring.js',
  },
  {
    name: 'api/services/notificationPreferences.js',
    category: 'api',
    status: 'prod',
    loc: 622,
    description: 'Service NotificationPreferences',
    dependencies: ['storage', 'realtimeNotifications'],
    path: 'api/services/notificationPreferences.js',
  },
  {
    name: 'api/services/notifications.js',
    category: 'api',
    status: 'prod',
    loc: 594,
    description: 'Service Notifications',
    dependencies: ['audit'],
    path: 'api/services/notifications.js',
  },
  {
    name: 'api/services/openApiGenerator.js',
    category: 'api',
    status: 'prod',
    loc: 616,
    description: 'Service OpenApiGenerator',
    dependencies: [],
    path: 'api/services/openApiGenerator.js',
  },
  {
    name: 'api/services/postgres-migrations.js',
    category: 'api',
    status: 'prod',
    loc: 358,
    description: 'Service Postgres Migrations',
    dependencies: [],
    path: 'api/services/postgres-migrations.js',
  },
  {
    name: 'api/services/postgres-shop.js',
    category: 'api',
    status: 'prod',
    loc: 547,
    description: 'Service Postgres Shop',
    dependencies: ['postgres', 'storage'],
    path: 'api/services/postgres-shop.js',
  },
  {
    name: 'api/services/postgres.js',
    category: 'api',
    status: 'prod',
    loc: 479,
    description: 'Service Postgres',
    dependencies: ['storage', 'postgres-migrations', 'postgres-shop'],
    path: 'api/services/postgres.js',
  },
  {
    name: 'api/services/priorityFee.js',
    category: 'api',
    status: 'prod',
    loc: 633,
    description: 'Service PriorityFee',
    dependencies: ['audit'],
    path: 'api/services/priorityFee.js',
  },
  {
    name: 'api/services/progression.js',
    category: 'api',
    status: 'prod',
    loc: 734,
    description: 'Service Progression',
    dependencies: ['audit'],
    path: 'api/services/progression.js',
  },
  {
    name: 'api/services/pushNotifications.js',
    category: 'api',
    status: 'prod',
    loc: 620,
    description: 'Service PushNotifications',
    dependencies: ['storage', 'notificationPreferences', 'audit'],
    path: 'api/services/pushNotifications.js',
  },
  {
    name: 'api/services/queue.js',
    category: 'api',
    status: 'prod',
    loc: 573,
    description: 'Service Queue',
    dependencies: ['audit'],
    path: 'api/services/queue.js',
  },
  {
    name: 'api/services/ratelimit.js',
    category: 'api',
    status: 'prod',
    loc: 666,
    description: 'Service Ratelimit',
    dependencies: ['audit'],
    path: 'api/services/ratelimit.js',
  },
  {
    name: 'api/services/realtimeNotifications.js',
    category: 'api',
    status: 'prod',
    loc: 842,
    description: 'Service RealtimeNotifications',
    dependencies: ['storage', 'audit'],
    path: 'api/services/realtimeNotifications.js',
  },
  {
    name: 'api/services/referrals.js',
    category: 'api',
    status: 'prod',
    loc: 449,
    description: 'Service Referrals',
    dependencies: ['audit'],
    path: 'api/services/referrals.js',
  },
  {
    name: 'api/services/rpcBatcher.js',
    category: 'api',
    status: 'prod',
    loc: 633,
    description: 'Service RpcBatcher',
    dependencies: ['audit'],
    path: 'api/services/rpcBatcher.js',
  },
  {
    name: 'api/services/rpcFailover.js',
    category: 'api',
    status: 'prod',
    loc: 751,
    description: 'Service RpcFailover',
    dependencies: ['audit'],
    path: 'api/services/rpcFailover.js',
  },
  {
    name: 'api/services/scheduler.js',
    category: 'api',
    status: 'prod',
    loc: 518,
    description: 'Service Scheduler',
    dependencies: ['audit'],
    path: 'api/services/scheduler.js',
  },
  {
    name: 'api/services/security.js',
    category: 'api',
    status: 'prod',
    loc: 410,
    description: 'Service Security',
    dependencies: ['audit'],
    path: 'api/services/security.js',
  },
  {
    name: 'api/services/sessionManager.js',
    category: 'api',
    status: 'prod',
    loc: 572,
    description: 'Service SessionManager',
    dependencies: [],
    path: 'api/services/sessionManager.js',
  },
  {
    name: 'api/services/shop.js',
    category: 'api',
    status: 'prod',
    loc: 465,
    description: 'Service Shop',
    dependencies: ['helius', 'auth'],
    path: 'api/services/shop.js',
  },
  {
    name: 'api/services/shopV2.js',
    category: 'api',
    status: 'prod',
    loc: 672,
    description: 'Service ShopV2',
    dependencies: ['postgres', 'storage'],
    path: 'api/services/shopV2.js',
  },
  {
    name: 'api/services/shutdown.js',
    category: 'api',
    status: 'prod',
    loc: 471,
    description: 'Service Shutdown',
    dependencies: ['audit', 'cache', 'queue', 'scheduler', 'healthcheck'],
    path: 'api/services/shutdown.js',
  },
  {
    name: 'api/services/storage.js',
    category: 'api',
    status: 'prod',
    loc: 1147,
    description: 'Service Storage',
    dependencies: [],
    path: 'api/services/storage.js',
  },
  {
    name: 'api/services/tokenMetadata.js',
    category: 'api',
    status: 'prod',
    loc: 513,
    description: 'Service TokenMetadata',
    dependencies: ['audit'],
    path: 'api/services/tokenMetadata.js',
  },
  {
    name: 'api/services/tracing.js',
    category: 'api',
    status: 'prod',
    loc: 707,
    description: 'Service Tracing',
    dependencies: [],
    path: 'api/services/tracing.js',
  },
  {
    name: 'api/services/transactionBuilder.js',
    category: 'api',
    status: 'prod',
    loc: 548,
    description: 'Service TransactionBuilder',
    dependencies: ['audit'],
    path: 'api/services/transactionBuilder.js',
  },
  {
    name: 'api/services/transactions.js',
    category: 'api',
    status: 'prod',
    loc: 466,
    description: 'Service Transactions',
    dependencies: ['audit', 'helius'],
    path: 'api/services/transactions.js',
  },
  {
    name: 'api/services/txMonitor.js',
    category: 'api',
    status: 'prod',
    loc: 702,
    description: 'Service TxMonitor',
    dependencies: ['audit', 'circuitbreaker', 'eventBus'],
    path: 'api/services/txMonitor.js',
  },
  {
    name: 'api/services/validator.js',
    category: 'api',
    status: 'prod',
    loc: 711,
    description: 'Service Validator',
    dependencies: ['audit'],
    path: 'api/services/validator.js',
  },
  {
    name: 'api/services/versioning.js',
    category: 'api',
    status: 'prod',
    loc: 481,
    description: 'Service Versioning',
    dependencies: ['audit'],
    path: 'api/services/versioning.js',
  },
  {
    name: 'api/services/webhooks.js',
    category: 'api',
    status: 'prod',
    loc: 446,
    description: 'Service Webhooks',
    dependencies: ['audit', 'leaderboard', 'database'],
    path: 'api/services/webhooks.js',
  },
  {
    name: 'api/services/wsBroadcast.js',
    category: 'api',
    status: 'prod',
    loc: 609,
    description: 'Service WsBroadcast',
    dependencies: ['eventBus', 'realtimeNotifications', 'audit'],
    path: 'api/services/wsBroadcast.js',
  },
  {
    name: 'api/services/wsManager.js',
    category: 'api',
    status: 'prod',
    loc: 686,
    description: 'Service WsManager',
    dependencies: ['audit'],
    path: 'api/services/wsManager.js',
  },
];
window.ECOSYSTEM_STATS = {
  generated: '2026-02-17T14:02:11.100Z',
  total: 339,
  pages: 24,
  css: 29,
  js: 133,
  games: 72,
  api: 81,
  godFiles: 1,
  totalLOC: 166495,
};
